export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

default_linemode devicons
default_linemode devicons

# compton -b
compton --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc --unredir-if-possible &
ibus-daemon --xim &
flameshot &

exec dwm
