# export ZSH="/root/.oh-my-zsh"
# export PATH=/usr/local/bin:$PATH
# modify TERM for autosuggestion plugin
export TERM=xterm-256color

# ZSH_THEME="ys"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
        # git
        zsh-autosuggestions
        autojump
        zsh-syntax-highlighting
        # hitokoto
        extract
	 )

# source this file after plugins
source $ZSH/oh-my-zsh.sh

# alias ohmyzsh="mate ~/.oh-my-zsh"
function wrm () {
    mv $1 .Trash
    }

function wp () {
    python3 ~/repo/pclip/pclips.py $1 $2
    }

function wgit () {
        wget "https://gh.api.99988866.xyz/"$1
}

function wps () {
    ps -aux | grep -v grep | grep $1
}

alias gls="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias vim="nvim"
alias ra="ranger"
alias c="clear"
alias s="neofetch"
alias lg="lazygit"
alias e="extract"
export EDITOR="nvim"
# add fzf
# source $HOME/.fzf.zsh

# alias for proxy
alias proxy_on='export all_proxy=socks5://127.0.0.1:23333'
alias proxy_off='unset all_proxy'

# alias for amixer: control audio
alias vu='amixer set Master 5%+'
alias vd='amixer set Master 5%-'
alias vt='amixer set Master toggle'

# fzf
# export FZF_DEFAULT_OPTS='--bind=ctrl-t:top,change:top --bind ctrl-e:down,ctrl-u:up'
# use ccat for preview: https://github.com/owenthereal/ccat/releases/download/v1.1.0/linux-amd64-1.1.0.tar.gz 
export FZF_DEFAULT_OPTS='--preview "[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500"'
# export FZF_DEFAULT_COMMAND='fd'
# ag -> use "the_silver_searcher"
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_COMPLETION_TRIGGER='\'
export FZF_TMUX=1
export FZF_TMUX_HEIGHT='80%'
export fzf_preview_cmd='[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'

# source completion and key-bindings
source ~/.config/zsh/completion.zsh
source ~/.config/zsh/key-bindings.zsh
